---
# yamllint disable-line rule:line-length
# .. seealso:: https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta
namespace: ssato
name: infraspec
version: 0.1.0
description: A collection of extra test and filter plugins for InfraCI
readme: README.md
authors:
  - Satoru SATOH (https://github.com/ssato/)
dependencies: []
license:
  - MIT
license_file: LICENSE.MIT
tags:
  - collection
  - utility
  - test
  - infraci

homepage: https://github.com/ssato/ansible-collection-infraspec
repository: https://github.com/ssato/ansible-collection-infraspec
issues: https://github.com/ssato/ansible-collection-infraspec/issues

# vim:sw=2:ts=2:et:
